name: Test authentication

on:
  workflow_dispatch:

jobs:
  call-authentication-check:
    name: Call Authentication Workflow
    uses: jzubiri-va/reusable-permissions-test/.github/workflows/pipeline.yml@main