name: Test authentication

on:
  workflow_dispatch:

jobs:
  name: Call Authentication Workflow
  call-authentication-check:
    uses: jzubiri-va/reusable-permissions-test/.github/workflows/pipeline.yml